# Generated by Django 5.1.7 on 2025-03-29 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('profile_id', models.CharField(max_length=8, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('girl', 'Girl'), ('boy', 'Boy')], max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('indonesia', 'Indonesia'), ('singapore', 'Singapore')], max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=10, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
