# Generated by Django 5.1.7 on 2025-04-01 15:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_id',
            field=models.CharField(default=api.models.generate_profile_id, max_length=8, unique=True),
        ),
    ]
