# Generated by Django 5.1.7 on 2025-04-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_promotion_customuser_balance_bankaccount_oilsale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsale',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, default=6336.0, editable=False, max_digits=5),
        ),
    ]
