# Generated by Django 5.1.7 on 2025-04-02 08:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_oilsale_price_per_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilsale',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, default=Decimal('6336.00'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='oilsale',
            name='total_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=100),
        ),
    ]
