# Generated by Django 5.1.7 on 2025-04-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
