# Generated by Django 5.1.7 on 2025-04-11 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_remove_promotion_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='items',
            field=models.ManyToManyField(to='api.cart'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('BCA', 'BCA'), ('OCBC', 'OCBC'), ('WALLET', 'RenuOil Wallet')], default='BCA', max_length=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=1200, max_digits=10),
        ),
    ]
