# Generated by Django 5.1.7 on 2025-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userpromousage'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='transactionhistory',
        #     name='bank_account',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        migrations.AddField(
            model_name='transactionhistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('bca', 'BCA'), ('OCBC', 'OCBC'), ('bni', 'BNI'), ('mandiri', 'mandiri'), ('WALLET', 'RenuOil Wallet')], default='BCA', max_length=10),
        ),
        migrations.AlterField(
            model_name='topup',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
    ]
