# Generated by Django 5.1.7 on 2025-04-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_transactionhistory_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='promotion/'),
        ),
    ]
