# Generated by Django 5.1.7 on 2025-04-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_promotion_picture_transactionhistory_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
