# Generated by Django 5.1.7 on 2025-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_product_picture_transactionhistory_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CO', 'Cooking Oil'), ('MO', 'Motor Oil'), ('IO', 'Industrial Oil')], default='CO', max_length=2),
        ),
    ]
