# Generated by Django 5.1.7 on 2025-04-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_product_category_transactionhistory_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    
    ]
