# Generated by Django 5.1.7 on 2025-04-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_promotion_is_used_transactionhistory_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_used',
        ),
 
        migrations.AddField(
            model_name='userpromousage',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
