# Generated by Django 5.1.7 on 2025-04-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_promotion_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping_method',
            field=models.CharField(choices=[('gojek', 'Gojek'), ('grab', 'Grab')], default='gojek', max_length=10),
        ),
   
    ]
