# Generated by Django 5.1.7 on 2025-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_transactionhistory_bank_account_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
       
        migrations.AlterField(
            model_name='tracker',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tanggal_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tanggal_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
