# Generated by Django 5.1.7 on 2025-04-21 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_tracker_created_at_transactionhistory_bank_account_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='tracker',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
