# Generated by Django 5.1.7 on 2025-04-24 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_transactionhistory_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='product_name',
        ),
        migrations.AddField(
            model_name='tracker',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
    
        migrations.AlterField(
            model_name='tracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to=settings.AUTH_USER_MODEL),
        ),
    ]
