# Generated by Django 5.1.7 on 2025-04-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_tracker_product_name_tracker_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('success', 'Success')], default='pending', max_length=10, null=True),
        ),
    
        
    ]
