# Generated by Django 5.1.7 on 2025-04-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_review_created_at_review_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='stock',
            field=models.IntegerField(default=500),
        ),
 
    ]
