# Generated by Django 5.1.7 on 2025-04-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_review_sold_review_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=500),
        ),
    ]
