# Generated by Django 5.1.7 on 2025-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_review_sold_remove_review_stock_product_sold_and_more'),
    ]

    operations = [
      
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('bca', 'BCA'), ('ocbc', 'OCBC'), ('bni', 'BNI'), ('mandiri', 'mandiri'), ('WALLET', 'RenuOil Wallet')], default='BCA', max_length=10),
        ),
    ]
