# Generated by Django 5.1.1 on 2025-04-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_transactionhistory_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
